### PR TITLE
Adds Support for Sounding Rockets

### PR DESCRIPTION
**Pull request by blnk2007**

### CODE REVIEW

**Comment by StupidChris** [comment]
???????

**Comment by blnk2007** [comment]
I'm not sure what your question is. This adds RealChute Modules to USI Sounding Rockets.

**Comment by StupidChris** [comment]
You came out of nowhere, adding MM patches I know nothing about, without announcing anything, what it's for, if it has been tested, and hope I would just merge the changes blindly?

**Comment by blnk2007** [comment]
Ok, you don't have to use it. Not sure why I would pull request without it
being tested. It looked like you were creating a repository of configs for
different mods. Most people in the KSP community are open to pull requests.
The title is pretty self explanatory. This is adding RealChute modules to
USI sounding rockets. Didn't really think it needed much more explanation
than that and didn't need a big announcement.

**Comment by sumghai** [comment]
I'm backing @StupidChris on this one.

I myself am also open to pull requests for my projects, but I'd want them to also at least include some sort of summary of the proposed changes and the reasoning behind them - this is so that we as project maintainers can double-check submitted work for issues (such as the aforementioned radial chute config).

**Comment by StupidChris** [comment]
@blnk2007 you'd be very surprised how many dumb and pointless issues/pull requests are actually created here. While the title does help, I'd at least like to know what I'm merging. Then again, as mentioned, your pull request *is* bugged, and you most certainly have not properly tested it. There is no way the radial pack chute works as it is in your current PR. I'll consider the merge, but I doubt it'll be needed with the RealChute2 changes

**Comment by blnk2007** [comment]
This is tested and is working with both FAR and Stock Aero.

**Comment by StupidChris** [comment]
Development on RealChute 1 has been stopped and the module has changed in RealChute 2, closing.

**Pull request closed without merging**
